### ISSUE TITLE
feature suggestion: kotlin version

### ISSUE THREAD

**Issue by mahmoudparandeh** [DenisovAV/deep_links_flutter#2]
as you know, new template is based on kotlin. is it possible to rewrite your code so that working with kotlin?

**Comment by DenisovAV** [comment]
Thank you for your question. Yes I'm going to make an update with the version of the provider and with Kotlin code

**Comment by DenisovAV** [comment]
Sorry for the delay. I've moved the project from Java to Kotlin and updated the android part for work with the latest version of Flutter. Thank you for your feature suggestion again.
